theme = "horizon"

[editor]
line-number = "relative"
mouse = false
middle-click-paste = false
shell = ["fish", "-c"]
cursorline = false
cursorcolumn = false
bufferline = "multiple"
popup-border = "all"
color-modes = true
auto-format = true

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "spinner",
  "version-control",
  "spacer",
  "workspace-diagnostics",
]
center = ["read-only-indicator", "file-name", "file-modification-indicator"]
right = [
  "selections",
  "position",
  "position-percentage",
  "file-encoding",
  "file-type",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = true
git-ignore = true
git-global = true
git-exclude = true
# max-depth = 5

[keys.insert]
j = { k = "normal_mode" }
